### ISSUE TITLE
Создание нового графического интерфейса для приложения. Адаптация под различные устройства

### ISSUE THREAD

**Issue by dddosha341** [dddosha341/SilenceChatV3#4]
Требуется создать красивый и понятный интерфейс для пользователя с различными анимациями

**Comment by Cifitt** [comment]
Интерфейс странички Login и Loading настроен окончательно. Протестировал на Android 14 и Windows 11. Ошибок не найдено

**Comment by Cifitt** [comment]
Адаптировал оставшиеся страницы на на Android 14 и Windows 11.
